import type { PlatformEventType } from "@/features/core/events/types";

/** Default UI copy keys under events.catalog.* — resolved at publish time. */
export const EVENT_CATALOG: Record<
  PlatformEventType,
  {
    titleKey: string;
    messageKey: string;
    descriptionKey: string;
    entityType: string;
    defaultVisibility: "owner" | "staff" | "manager_scoped";
  }
> = {
  "application.created": {
    titleKey: "applicationCreatedTitle",
    messageKey: "applicationCreatedMessage",
    descriptionKey: "applicationCreatedDescription",
    entityType: "application",
    defaultVisibility: "staff",
  },
  "application.updated": {
    titleKey: "applicationUpdatedTitle",
    messageKey: "applicationUpdatedMessage",
    descriptionKey: "applicationUpdatedDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "application.status_changed": {
    titleKey: "applicationStatusTitle",
    messageKey: "applicationStatusMessage",
    descriptionKey: "applicationStatusDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "application.assigned": {
    titleKey: "applicationAssignedTitle",
    messageKey: "applicationAssignedMessage",
    descriptionKey: "applicationAssignedDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "creator.created": {
    titleKey: "creatorCreatedTitle",
    messageKey: "creatorCreatedMessage",
    descriptionKey: "creatorCreatedDescription",
    entityType: "creator",
    defaultVisibility: "staff",
  },
  "creator.updated": {
    titleKey: "creatorUpdatedTitle",
    messageKey: "creatorUpdatedMessage",
    descriptionKey: "creatorUpdatedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.assigned": {
    titleKey: "creatorAssignedTitle",
    messageKey: "creatorAssignedMessage",
    descriptionKey: "creatorAssignedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.status_changed": {
    titleKey: "creatorStatusTitle",
    messageKey: "creatorStatusMessage",
    descriptionKey: "creatorStatusDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.avatar_changed": {
    titleKey: "creatorAvatarTitle",
    messageKey: "creatorAvatarMessage",
    descriptionKey: "creatorAvatarDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.profile_updated": {
    titleKey: "creatorProfileTitle",
    messageKey: "creatorProfileMessage",
    descriptionKey: "creatorProfileDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.document_uploaded": {
    titleKey: "creatorDocumentTitle",
    messageKey: "creatorDocumentMessage",
    descriptionKey: "creatorDocumentDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.platform_added": {
    titleKey: "creatorPlatformTitle",
    messageKey: "creatorPlatformMessage",
    descriptionKey: "creatorPlatformDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.archived": {
    titleKey: "creatorArchivedTitle",
    messageKey: "creatorArchivedMessage",
    descriptionKey: "creatorArchivedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.deleted": {
    titleKey: "creatorDeletedTitle",
    messageKey: "creatorDeletedMessage",
    descriptionKey: "creatorDeletedDescription",
    entityType: "creator",
    defaultVisibility: "staff",
  },
  "manager.changed": {
    titleKey: "creatorAssignedTitle",
    messageKey: "creatorAssignedMessage",
    descriptionKey: "creatorAssignedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "status.changed": {
    titleKey: "creatorStatusTitle",
    messageKey: "creatorStatusMessage",
    descriptionKey: "creatorStatusDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "staff.login": {
    titleKey: "staffLoginTitle",
    messageKey: "staffLoginMessage",
    descriptionKey: "staffLoginDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.logout": {
    titleKey: "staffLogoutTitle",
    messageKey: "staffLogoutMessage",
    descriptionKey: "staffLogoutDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.created": {
    titleKey: "staffCreatedTitle",
    messageKey: "staffCreatedMessage",
    descriptionKey: "staffCreatedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.updated": {
    titleKey: "staffUpdatedTitle",
    messageKey: "staffUpdatedMessage",
    descriptionKey: "staffUpdatedDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.deleted": {
    titleKey: "staffDeletedTitle",
    messageKey: "staffDeletedMessage",
    descriptionKey: "staffDeletedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.role_changed": {
    titleKey: "staffRoleTitle",
    messageKey: "staffRoleMessage",
    descriptionKey: "staffRoleDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.department_changed": {
    titleKey: "staffDepartmentTitle",
    messageKey: "staffDepartmentMessage",
    descriptionKey: "staffDepartmentDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.status_changed": {
    titleKey: "staffStatusTitle",
    messageKey: "staffStatusMessage",
    descriptionKey: "staffStatusDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.assigned_creator": {
    titleKey: "staffAssignedCreatorTitle",
    messageKey: "staffAssignedCreatorMessage",
    descriptionKey: "staffAssignedCreatorDescription",
    entityType: "profile",
    defaultVisibility: "manager_scoped",
  },
  "staff.unassigned_creator": {
    titleKey: "staffUnassignedCreatorTitle",
    messageKey: "staffUnassignedCreatorMessage",
    descriptionKey: "staffUnassignedCreatorDescription",
    entityType: "profile",
    defaultVisibility: "manager_scoped",
  },
  "employee.created": {
    titleKey: "employeeCreatedTitle",
    messageKey: "employeeCreatedMessage",
    descriptionKey: "employeeCreatedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "employee.updated": {
    titleKey: "employeeUpdatedTitle",
    messageKey: "employeeUpdatedMessage",
    descriptionKey: "employeeUpdatedDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "employee.deleted": {
    titleKey: "employeeDeletedTitle",
    messageKey: "employeeDeletedMessage",
    descriptionKey: "employeeDeletedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "employee.suspended": {
    titleKey: "employeeSuspendedTitle",
    messageKey: "employeeSuspendedMessage",
    descriptionKey: "employeeSuspendedDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "employee.activated": {
    titleKey: "employeeActivatedTitle",
    messageKey: "employeeActivatedMessage",
    descriptionKey: "employeeActivatedDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "finance.transaction.created": {
    titleKey: "financeTxCreatedTitle",
    messageKey: "financeTxCreatedMessage",
    descriptionKey: "financeTxCreatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.updated": {
    titleKey: "financeTxUpdatedTitle",
    messageKey: "financeTxUpdatedMessage",
    descriptionKey: "financeTxUpdatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.deleted": {
    titleKey: "financeTxDeletedTitle",
    messageKey: "financeTxDeletedMessage",
    descriptionKey: "financeTxDeletedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "staff",
  },
  "finance.transaction.status_changed": {
    titleKey: "financeTxStatusTitle",
    messageKey: "financeTxStatusMessage",
    descriptionKey: "financeTxStatusDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.assigned": {
    titleKey: "financeTxAssignedTitle",
    messageKey: "financeTxAssignedMessage",
    descriptionKey: "financeTxAssignedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.created": {
    titleKey: "financePayoutCreatedTitle",
    messageKey: "financePayoutCreatedMessage",
    descriptionKey: "financePayoutCreatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.updated": {
    titleKey: "financePayoutUpdatedTitle",
    messageKey: "financePayoutUpdatedMessage",
    descriptionKey: "financePayoutUpdatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.paid": {
    titleKey: "financePayoutPaidTitle",
    messageKey: "financePayoutPaidMessage",
    descriptionKey: "financePayoutPaidDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.cancelled": {
    titleKey: "financePayoutCancelledTitle",
    messageKey: "financePayoutCancelledMessage",
    descriptionKey: "financePayoutCancelledDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.requested": {
    titleKey: "financePayoutRequestedTitle",
    messageKey: "financePayoutRequestedMessage",
    descriptionKey: "financePayoutRequestedDescription",
    entityType: "creator_payout",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.approved": {
    titleKey: "financePayoutApprovedTitle",
    messageKey: "financePayoutApprovedMessage",
    descriptionKey: "financePayoutApprovedDescription",
    entityType: "creator_payout",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.rejected": {
    titleKey: "financePayoutRejectedTitle",
    messageKey: "financePayoutRejectedMessage",
    descriptionKey: "financePayoutRejectedDescription",
    entityType: "creator_payout",
    defaultVisibility: "manager_scoped",
  },
  "finance.balance.updated": {
    titleKey: "financeBalanceUpdatedTitle",
    messageKey: "financeBalanceUpdatedMessage",
    descriptionKey: "financeBalanceUpdatedDescription",
    entityType: "creator_payout",
    defaultVisibility: "manager_scoped",
  },
  "task.created": {
    titleKey: "taskCreatedTitle",
    messageKey: "taskCreatedMessage",
    descriptionKey: "taskCreatedDescription",
    entityType: "task",
    defaultVisibility: "staff",
  },
  "task.updated": {
    titleKey: "taskUpdatedTitle",
    messageKey: "taskUpdatedMessage",
    descriptionKey: "taskUpdatedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.assigned": {
    titleKey: "taskAssignedTitle",
    messageKey: "taskAssignedMessage",
    descriptionKey: "taskAssignedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.completed": {
    titleKey: "taskCompletedTitle",
    messageKey: "taskCompletedMessage",
    descriptionKey: "taskCompletedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.deleted": {
    titleKey: "taskDeletedTitle",
    messageKey: "taskDeletedMessage",
    descriptionKey: "taskDeletedDescription",
    entityType: "task",
    defaultVisibility: "staff",
  },
  "task.status_changed": {
    titleKey: "taskStatusChangedTitle",
    messageKey: "taskStatusChangedMessage",
    descriptionKey: "taskStatusChangedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.comment.created": {
    titleKey: "taskCommentCreatedTitle",
    messageKey: "taskCommentCreatedMessage",
    descriptionKey: "taskCommentCreatedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.comment.updated": {
    titleKey: "taskCommentUpdatedTitle",
    messageKey: "taskCommentUpdatedMessage",
    descriptionKey: "taskCommentUpdatedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.comment.deleted": {
    titleKey: "taskCommentDeletedTitle",
    messageKey: "taskCommentDeletedMessage",
    descriptionKey: "taskCommentDeletedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.attachment.uploaded": {
    titleKey: "taskAttachmentUploadedTitle",
    messageKey: "taskAttachmentUploadedMessage",
    descriptionKey: "taskAttachmentUploadedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.attachment.deleted": {
    titleKey: "taskAttachmentDeletedTitle",
    messageKey: "taskAttachmentDeletedMessage",
    descriptionKey: "taskAttachmentDeletedDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
  "task.duplicated": {
    titleKey: "taskDuplicatedTitle",
    messageKey: "taskDuplicatedMessage",
    descriptionKey: "taskDuplicatedDescription",
    entityType: "task",
    defaultVisibility: "staff",
  },
  "task.deadline_approaching": {
    titleKey: "taskDeadlineApproachingTitle",
    messageKey: "taskDeadlineApproachingMessage",
    descriptionKey: "taskDeadlineApproachingDescription",
    entityType: "task",
    defaultVisibility: "manager_scoped",
  },
};
