import type { PlatformEventType } from "@/features/core/events/types";

/** Default UI copy keys under events.catalog.* — resolved at publish time. */
export const EVENT_CATALOG: Record<
  PlatformEventType,
  {
    titleKey: string;
    messageKey: string;
    descriptionKey: string;
    entityType: string;
    defaultVisibility: "owner" | "staff" | "manager_scoped";
  }
> = {
  "application.created": {
    titleKey: "applicationCreatedTitle",
    messageKey: "applicationCreatedMessage",
    descriptionKey: "applicationCreatedDescription",
    entityType: "application",
    defaultVisibility: "staff",
  },
  "application.updated": {
    titleKey: "applicationUpdatedTitle",
    messageKey: "applicationUpdatedMessage",
    descriptionKey: "applicationUpdatedDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "application.status_changed": {
    titleKey: "applicationStatusTitle",
    messageKey: "applicationStatusMessage",
    descriptionKey: "applicationStatusDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "application.assigned": {
    titleKey: "applicationAssignedTitle",
    messageKey: "applicationAssignedMessage",
    descriptionKey: "applicationAssignedDescription",
    entityType: "application",
    defaultVisibility: "manager_scoped",
  },
  "creator.created": {
    titleKey: "creatorCreatedTitle",
    messageKey: "creatorCreatedMessage",
    descriptionKey: "creatorCreatedDescription",
    entityType: "creator",
    defaultVisibility: "staff",
  },
  "creator.updated": {
    titleKey: "creatorUpdatedTitle",
    messageKey: "creatorUpdatedMessage",
    descriptionKey: "creatorUpdatedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.assigned": {
    titleKey: "creatorAssignedTitle",
    messageKey: "creatorAssignedMessage",
    descriptionKey: "creatorAssignedDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.status_changed": {
    titleKey: "creatorStatusTitle",
    messageKey: "creatorStatusMessage",
    descriptionKey: "creatorStatusDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.avatar_changed": {
    titleKey: "creatorAvatarTitle",
    messageKey: "creatorAvatarMessage",
    descriptionKey: "creatorAvatarDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.profile_updated": {
    titleKey: "creatorProfileTitle",
    messageKey: "creatorProfileMessage",
    descriptionKey: "creatorProfileDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.document_uploaded": {
    titleKey: "creatorDocumentTitle",
    messageKey: "creatorDocumentMessage",
    descriptionKey: "creatorDocumentDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "creator.platform_added": {
    titleKey: "creatorPlatformTitle",
    messageKey: "creatorPlatformMessage",
    descriptionKey: "creatorPlatformDescription",
    entityType: "creator",
    defaultVisibility: "manager_scoped",
  },
  "staff.login": {
    titleKey: "staffLoginTitle",
    messageKey: "staffLoginMessage",
    descriptionKey: "staffLoginDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.logout": {
    titleKey: "staffLogoutTitle",
    messageKey: "staffLogoutMessage",
    descriptionKey: "staffLogoutDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.created": {
    titleKey: "staffCreatedTitle",
    messageKey: "staffCreatedMessage",
    descriptionKey: "staffCreatedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.updated": {
    titleKey: "staffUpdatedTitle",
    messageKey: "staffUpdatedMessage",
    descriptionKey: "staffUpdatedDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.deleted": {
    titleKey: "staffDeletedTitle",
    messageKey: "staffDeletedMessage",
    descriptionKey: "staffDeletedDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.role_changed": {
    titleKey: "staffRoleTitle",
    messageKey: "staffRoleMessage",
    descriptionKey: "staffRoleDescription",
    entityType: "profile",
    defaultVisibility: "owner",
  },
  "staff.department_changed": {
    titleKey: "staffDepartmentTitle",
    messageKey: "staffDepartmentMessage",
    descriptionKey: "staffDepartmentDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.status_changed": {
    titleKey: "staffStatusTitle",
    messageKey: "staffStatusMessage",
    descriptionKey: "staffStatusDescription",
    entityType: "profile",
    defaultVisibility: "staff",
  },
  "staff.assigned_creator": {
    titleKey: "staffAssignedCreatorTitle",
    messageKey: "staffAssignedCreatorMessage",
    descriptionKey: "staffAssignedCreatorDescription",
    entityType: "profile",
    defaultVisibility: "manager_scoped",
  },
  "staff.unassigned_creator": {
    titleKey: "staffUnassignedCreatorTitle",
    messageKey: "staffUnassignedCreatorMessage",
    descriptionKey: "staffUnassignedCreatorDescription",
    entityType: "profile",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.created": {
    titleKey: "financeTxCreatedTitle",
    messageKey: "financeTxCreatedMessage",
    descriptionKey: "financeTxCreatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.updated": {
    titleKey: "financeTxUpdatedTitle",
    messageKey: "financeTxUpdatedMessage",
    descriptionKey: "financeTxUpdatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.deleted": {
    titleKey: "financeTxDeletedTitle",
    messageKey: "financeTxDeletedMessage",
    descriptionKey: "financeTxDeletedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "staff",
  },
  "finance.transaction.status_changed": {
    titleKey: "financeTxStatusTitle",
    messageKey: "financeTxStatusMessage",
    descriptionKey: "financeTxStatusDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.transaction.assigned": {
    titleKey: "financeTxAssignedTitle",
    messageKey: "financeTxAssignedMessage",
    descriptionKey: "financeTxAssignedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.created": {
    titleKey: "financePayoutCreatedTitle",
    messageKey: "financePayoutCreatedMessage",
    descriptionKey: "financePayoutCreatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.updated": {
    titleKey: "financePayoutUpdatedTitle",
    messageKey: "financePayoutUpdatedMessage",
    descriptionKey: "financePayoutUpdatedDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.paid": {
    titleKey: "financePayoutPaidTitle",
    messageKey: "financePayoutPaidMessage",
    descriptionKey: "financePayoutPaidDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
  "finance.payout.cancelled": {
    titleKey: "financePayoutCancelledTitle",
    messageKey: "financePayoutCancelledMessage",
    descriptionKey: "financePayoutCancelledDescription",
    entityType: "finance_transaction",
    defaultVisibility: "manager_scoped",
  },
};
